### ISSUE TITLE
no docker-compose.yml

### ISSUE THREAD

**Issue by dv336699** [round-robin-books/gently-kafka#1]
Thanks for making this.

There seems to be no docker file in this repository?

Command seen on 
https://www.gentlydownthe.stream/#/10/1

**Comment by OneCricketeer** [comment]
Closed with https://github.com/round-robin-books/gently-kafka/commit/08dbd1b57c18f5dd3da09a818faccb6cf8553f13

**Comment by round-robin-books** [comment]
I added the missing docker-compose file :)
